export const SOURCE_AMOUNT_CHANGED = 'welcome/SOURCE_AMOUNT_CHANGED'
export const SOURCE_CURRENCY_CHANGED = 'welcome/SOURCE_CURRENCY_CHANGED'
export const DESTINATION_AMOUNT_CHANGED = 'welcome/DESTINATION_AMOUNT_CHANGED'
export const DESTINATION_CURRENCY_CHANGED = 'welcome/DESTINATION_CURRENCY_CHANGED'

export const GET_CURRENCIES = 'welcome/GET_CURRENCIES'

export const GET_CURRENCIES_REQUEST = 'welcome/GET_CURRENCIES_REQUEST'
export const GET_CURRENCIES_SUCCESS = 'welcome/GET_CURRENCIES_SUCCESS'
export const GET_CURRENCIES_FAILED = 'welcome/GET_CURRENCIES_FAILED'

export const GET_RATES_REQUEST = 'welcome/GET_RATES_REQUEST'
export const GET_RATES_SUCCESS = 'welcome/GET_RATES_SUCCESS'
export const GET_RATES_FAILED = 'welcome/GET_RATES_FAILED'
